// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6f92f236-6136-4635-8989-cff9f424a327",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Hfkam8Gzc",
    "aws_user_pools_web_client_id": "6t9hq92autrv1sdobqpq0anhma",
    "oauth": {}
};


export default awsmobile;
